### ISSUE TITLE
在最新的稳定版 `v5.2.3` 的 Release 中缺少 macos-runtime 以及 macos OTA 包

### ISSUE THREAD

**Issue by wangl-cc** [MaaAssistantArknights/MaaRelease#117]
### issue 正文：

没有 macos-runtime 包会导致 CLI 在 macOS 上无法安装 Core， OTA 包可能会影响 mac GUI 的更新。

https://github.com/MaaAssistantArknights/MaaRelease/releases/tag/v5.2.3

https://github.com/MaaAssistantArknights/MaaRelease/releases/tag/v5.2.2

**Comment by AnnAngela** [comment]
https://github.com/MaaAssistantArknights/MaaAssistantArknights/actions/runs/9014434724/job/24767114984
重试了
