### ISSUE TITLE
Adding version.json to the resources

### ISSUE THREAD

**Issue by Constrat** [MaaAssistantArknights/MaaRelease#34]
Is it possible to also release the version.json to the client, like the tasks.json are?
I feel it's very important because with tasks.json we can implement event stage navigation, so the user can choose which event stages to farm, but the 
![image](https://github.com/MaaAssistantArknights/MaaRelease/assets/56174894/170b0175-8627-4017-8c86-37a6fe7a5906)
top bar is not updated, until the next major version, which doesn't happen often, and also doesn't usually happen together with events.

**Comment by AnnAngela** [comment]
The event name in the top bar is used to indicate to the user which event is fully supported by this version. The tasks.json can be used to update the navigation, but there are some things that need to be supported by the client itself, such as the new rogue and the recognition of new drops.

cc @MistEO

**Comment by MistEO** [comment]
The title is not used to tell the user which version of the game is now, but to tell the user which version is supported by the MAA you are using now. So it should be hot updated.

**Comment by Constrat** [comment]
So it's dependent on the version like the version object in the Stage Overview. Got it.

**Comment by Constrat** [comment]
Wait but now we are always using text recognition for event navigation. And usually, we implement the navigation the same day it drops via hot update.

**Comment by MistEO** [comment]
Yes, this is fragmented. So we also plan to upload other resources generated by the updater to the OTA server, but this may use a lot of traffic, so we are also considering uploading the difference parts for different versions. All in all it's a big project.

**Comment by Constrat** [comment]
No worries, I just wanted to get a quick insight and clarification 👍🏻
